# Generated by Django 4.2.16 on 2024-10-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='sponsor_type',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='contact_person',
            field=models.CharField(default='Kalumu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='email',
            field=models.EmailField(default='karolynkalumu@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='phone_number',
            field=models.CharField(default='0724356789', max_length=13),
            preserve_default=False,
        ),
    ]
