# Generated by Django 4.2.16 on 2024-11-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_alter_sponsor_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
