# Generated by Django 4.2.16 on 2024-11-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_sponsorship_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorship',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='sponsorship_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional amount for monetary sponsorship.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='sponsorship_description',
            field=models.TextField(default='I will give you guys goats, take them or leave it', help_text='Describe the type or nature of the sponsorship.'),
            preserve_default=False,
        ),
    ]
