# Generated by Django 4.2.16 on 2024-10-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='payment_confirmation_code',
            field=models.CharField(default='SWOL56RTK7', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='registration_type',
            field=models.CharField(choices=[('sponsor', 'Sponsor'), ('friend', 'Friend of the car group'), ('member', 'Car group Member'), ('other', 'Other')], default='member', max_length=20),
            preserve_default=False,
        ),
    ]
